// All content below is original educational material written for this site.
const Q=[ // [subject, topic, difficulty, question, options, answerIndex, explanation]
["Psychopathology","Depressive Disorders","Easy","Which feature is most characteristic of a major depressive episode?",["Persistent elevated mood","Persistent low mood or loss of interest","Increased goal-directed activity","Reduced need for sleep without fatigue"],1,"Major depressive episodes centre on persistent low mood and/or loss of interest or pleasure, alongside other symptoms."],
["Psychopathology","Bipolar Disorders","Medium","What is required for a diagnosis of bipolar I disorder?",["At least one manic episode","A major depressive episode only","Two years of mild chronic low mood","Recurrent panic attacks"],0,"Bipolar I requires at least one manic episode. Depressive episodes are common but not required."],
["Psychopathology","Psychotic Disorders","Easy","A fixed false belief held despite clear contrary evidence is a:",["Delusion","Hallucination","Obsession","Phobia"],0,"Delusions are fixed false beliefs. Hallucinations are perceptions without an external stimulus."],
["Psychopathology","Trauma","Medium","Which symptom cluster is characteristic of PTSD?",["Intrusion and avoidance","Fixed grandiose beliefs","Binge eating","Motor tics"],0,"PTSD includes intrusion symptoms, avoidance, negative changes in mood/cognition, and arousal changes."],
["Anxiety & OCD","Generalised Anxiety","Easy","Excessive worry about many everyday matters that is hard to control best fits:",["Generalised anxiety disorder","Specific phobia","Panic disorder","Social anxiety disorder"],0,"GAD involves persistent, hard-to-control worry across multiple domains."],
["Anxiety & OCD","Panic Disorder","Medium","Recurrent unexpected panic attacks plus persistent worry about further attacks define:",["Panic disorder","Agoraphobia only","GAD","Illness anxiety disorder"],0,"Panic disorder requires unexpected attacks followed by ongoing concern or behavioural change."],
["Anxiety & OCD","OCD","Medium","In OCD, compulsions are best described as:",["Repetitive behaviours or mental acts performed to reduce distress from obsessions","Pleasurable habits","Unwanted images only","Psychotic experiences"],0,"Compulsions are repetitive acts performed in response to obsessions or rigid rules."],
["Assessment","Psychometrics","Easy","A test that gives consistent results over time shows high:",["Reliability","Validity","Prevalence","Incidence"],0,"Reliability is consistency. A test can be reliable without being valid."],
["Assessment","Screening","Medium","The sensitivity of a screening test is the proportion of:",["People with the condition who test positive","People without the condition who test negative","Positive results that are correct","People in the population with the condition"],0,"Sensitivity = true positives / all people who have the condition."],
["Assessment","Self-report Measures","Easy","Which is a widely used self-report measure of depressive symptoms?",["Beck Depression Inventory","Wechsler Adult Intelligence Scale","Stroop Test","Rorschach Inkblot Method"],0,"The BDI is a self-report symptom inventory. The WAIS measures cognitive ability."],
["Assessment","Mental Status Exam","Medium","In the mental status examination, the observable emotional expression is called:",["Affect","Mood","Insight","Thought form"],0,"Affect is observed by the clinician; mood is the person's own report."],
["Psychotherapy","CBT","Easy","Cognitive restructuring aims to:",["Identify and test unhelpful thoughts","Uncover repressed memories","Provide unconditional positive regard","Increase avoidance"],0,"Cognitive restructuring examines the evidence for and against unhelpful thoughts."],
["Psychotherapy","Exposure Therapy","Medium","Exposure therapy works mainly through:",["Repeated safe contact with feared stimuli","Dream interpretation","Avoidance of triggers","Medication adjustment"],0,"Repeated exposure without the feared outcome supports new inhibitory learning."],
["Psychotherapy","DBT","Medium","Dialectical behaviour therapy was originally developed for:",["Borderline personality disorder","Specific phobia","Dyslexia","Schizophrenia"],0,"DBT was developed for people with borderline personality disorder and intense emotion dysregulation."],
["Psychotherapy","Person-centred","Easy","Which are core conditions of person-centred therapy?",["Empathy, congruence, unconditional positive regard","Interpretation, free association, transference","Exposure, response prevention, homework","Reinforcement, shaping, extinction"],0,"Rogers described empathy, congruence and unconditional positive regard."],
["Psychotherapy","ACT","Medium","The central aim of Acceptance and Commitment Therapy is:",["Psychological flexibility","Eliminating all unpleasant thoughts","Insight into childhood conflicts","Symptom-free status"],0,"ACT builds flexible, values-guided action alongside acceptance."],
["Research & Statistics","Hypothesis Testing","Medium","A Type I error is:",["Rejecting a true null hypothesis","Failing to reject a false null hypothesis","Measuring the wrong variable","Using a biased sample"],0,"A Type I error is a false positive; a Type II error is a false negative."],
["Research & Statistics","Descriptive Statistics","Easy","Which measure of central tendency is least affected by outliers?",["Median","Mean","Range","Standard deviation"],0,"The median depends on rank order, not extreme values."],
["Research & Statistics","Correlation","Easy","A correlation of r = -0.80 indicates:",["A strong negative relationship","A weak positive relationship","No relationship","Causation"],0,"The sign gives direction and the magnitude gives strength. Correlation does not show causation."],
["Research & Statistics","Research Design","Medium","Random assignment mainly strengthens:",["Internal validity","External validity","Test-retest reliability","Sample size"],0,"Random assignment balances groups, supporting causal inference."],
["Ethics","Consent","Easy","Valid informed consent requires:",["Adequate information, capacity, and voluntariness","A signature only","Agreement from a relative","Consent given once and never revisited"],0,"Consent needs understanding, capacity, and freedom from coercion, and can be revisited."],
["Ethics","Confidentiality","Medium","Confidentiality may be limited when:",["There is serious risk of harm to self or others, per local law and policy","The client seems anxious","A friend asks","The session runs over time"],0,"Limits are explained at the start and follow local law and professional codes."],
["Ethics","Boundaries","Medium","Dual relationships with clients should generally be:",["Avoided when they risk exploitation or impaired objectivity","Encouraged","Kept secret","Ignored"],0,"Boundary crossings need careful judgement, consultation, and documentation."],
["Neuropsychology & Development","Executive Function","Easy","Executive functions include:",["Planning, inhibition, and working memory","Colour vision only","Reflex movements","Long-term storage of childhood memories"],0,"Executive functions coordinate goal-directed behaviour and are linked to frontal networks."],
["Neuropsychology & Development","Cognitive Development","Easy","In Piaget's theory, abstract reasoning emerges in the:",["Formal operational stage","Sensorimotor stage","Preoperational stage","Concrete operational stage"],0,"The formal operational stage begins around adolescence."]
];
const NOTES=[ // s = subject (matches question subjects), t = title, o = overview, k = key points, x = exam summary, m = misconception
{s:"Psychopathology",t:"Psychopathology: Mood, Psychotic and Trauma Disorders",o:"Psychopathology is the study of the nature, causes and course of mental disorders. Clinicians combine symptoms, duration, distress and impairment to reach a diagnosis.",k:["Major depressive episode: low mood or anhedonia plus other symptoms","Mania: elevated or irritable mood with increased energy; bipolar I requires one manic episode","Psychosis: delusions, hallucinations, disorganised thinking","PTSD: intrusion, avoidance, negative cognition/mood, arousal changes","Comorbidity (co-occurring conditions) is common"],x:"Match the symptom pattern to the disorder, and check duration and impairment.",m:"Sadness alone is not depression; hallucinations are not the same as delusions."},
{s:"Anxiety & OCD",t:"Anxiety Disorders and OCD",o:"Anxiety disorders involve excessive fear or worry with behavioural avoidance. OCD involves obsessions and compulsions and is classified separately in current manuals.",k:["GAD: widespread, hard-to-control worry","Panic disorder: unexpected panic attacks plus worry about more","Specific and social phobias: fear of objects or evaluation","OCD: obsessions drive compulsions","First-line psychological treatment: CBT with exposure (and response prevention for OCD)"],x:"Know the core feature of each disorder and the exposure-based treatment logic.",m:"Compulsions are not always visible; mental rituals count."},
{s:"Assessment",t:"Clinical Assessment, Interviewing and Psychometrics",o:"Assessment gathers information from interviews, observation, and standardised measures to form a clinical formulation.",k:["Reliability: consistency; validity: measures what it claims","Sensitivity: true positive rate; specificity: true negative rate","Mental status exam: appearance, behaviour, speech, mood/affect, thought, perception, cognition, insight","Screening tools are not diagnostic tools","Use multiple sources of information"],x:"Distinguish reliability from validity, and sensitivity from specificity.",m:"A reliable test is not automatically valid."},
{s:"Psychotherapy",t:"Psychotherapy Approaches",o:"Major approaches include CBT, behaviour therapy, psychodynamic, humanistic, ACT, DBT, family/systemic and interpersonal therapy. Common factors such as the therapeutic alliance predict outcomes across approaches.",k:["CBT: link thoughts, feelings and behaviour; cognitive restructuring; behavioural experiments","Behaviour therapy: learning principles, reinforcement, exposure","Psychodynamic: unconscious processes, transference","Person-centred: empathy, congruence, unconditional positive regard","ACT: acceptance, values, psychological flexibility","DBT: skills for distress tolerance and emotion regulation"],x:"Pair each therapy with its key technique and target problem.",m:"No single therapy is best for every client."},
{s:"Research & Statistics",t:"Research Methods and Statistics",o:"Research methods test claims about behaviour and treatment. Good design and sound statistics reduce bias and misinterpretation.",k:["Random assignment supports causal claims (internal validity)","Type I error: false positive; Type II: false negative","Median resists outliers","Correlation shows association, not causation","Report effect sizes and confidence intervals, not only p-values"],x:"Link design choices to the validity threats they address.",m:"A significant p-value does not mean a large or important effect."},
{s:"Ethics",t:"Professional Ethics",o:"Ethics guides safe, respectful practice. Codes from recognised professional bodies and local law set the standards.",k:["Informed consent: information, capacity, voluntariness","Confidentiality with limits explained early","Avoid exploitative dual relationships","Practise within competence and seek supervision","Keep accurate records"],x:"Identify the principle at stake, then choose the option that protects the client.",m:"Confidentiality is not absolute."},
{s:"Neuropsychology & Development",t:"Neuropsychology and Development",o:"Neuropsychology links brain function to cognition and behaviour. Developmental psychology describes change across the lifespan.",k:["Executive function: planning, inhibition, working memory","Neuroplasticity: brain change with experience","Piaget: sensorimotor, preoperational, concrete operational, formal operational","Attachment shapes early social development"],x:"Know key terms and the order of Piaget's stages.",m:"Brain regions work in networks rather than in isolation."}
];
const GLOSS=[ // [term, definition]
["Affect","Observable emotional expression during an interview."],
["Anhedonia","Reduced ability to feel pleasure or interest."],
["Cognition","Mental processes such as attention, memory, and reasoning."],
["Comorbidity","Co-occurrence of two or more conditions in the same person."],
["Delusion","Fixed false belief held despite contrary evidence."],
["Dissociation","Disruption in the normal integration of consciousness, memory, or identity."],
["Executive function","Higher-order skills such as planning, inhibition, and working memory."],
["Formulation","A hypothesis about why a person's difficulties developed and persist."],
["Hallucination","Perception-like experience without an external stimulus."],
["Incidence","Number of new cases in a population over a period of time."],
["Insight","Awareness of one's own condition and its effects."],
["Prevalence","Proportion of a population with a condition at a given time."],
["Reinforcement","A consequence that increases the likelihood of a behaviour."],
["Reliability","Consistency of a measure."],
["Rumination","Repetitive, passive dwelling on distress and its causes."],
["Sensitivity","Proportion of true cases correctly identified by a test."],
["Specificity","Proportion of non-cases correctly identified by a test."],
["Therapeutic alliance","Collaborative bond, agreement on goals, and agreement on tasks between client and therapist."],
["Transference","Client's re-experiencing of past relationship patterns with the therapist."],
["Validity","Extent to which a measure assesses what it claims to assess."]
];
Q.push(
["Psychopathology","Personality Disorders","Medium","Which pattern best describes borderline personality disorder?",["Unstable relationships, self-image and emotions with marked impulsivity","Detachment and restricted emotional expression only","Fear of negative evaluation in social settings","Fixed persecutory delusions"],0,"Borderline personality disorder involves pervasive instability in relationships, self-image and affect, with impulsivity."],
["Psychopathology","Eating Disorders","Medium","Recurrent binge eating with regular compensatory behaviours and overvaluation of weight or shape best fits:",["Bulimia nervosa","Restricting-type anorexia nervosa","Avoidant/restrictive food intake disorder","Rumination disorder"],0,"Bulimia nervosa combines binge eating, compensatory behaviours and body-image concerns."],
["Psychopathology","Substance Use","Medium","Tolerance in substance use means:",["Needing more of a substance to achieve the same effect","Symptoms after stopping the substance","Using in hazardous situations","Craving only"],0,"Tolerance is a reduced effect from the same dose. Withdrawal is the symptom syndrome after stopping."],
["Psychopathology","Depressive Disorders","Medium","Persistent depressive disorder requires depressed mood on most days for at least:",["Two years in adults","Two weeks","Six months","One month"],0,"Persistent depressive disorder is chronic low mood lasting at least two years in adults."],
["Anxiety & OCD","Social Anxiety","Easy","The core fear in social anxiety disorder is:",["Negative evaluation by others","Being alone","Open spaces only","Contamination"],0,"Social anxiety centres on fear of scrutiny, embarrassment or negative evaluation."],
["Anxiety & OCD","OCD","Medium","Which is a first-line psychological treatment for OCD?",["Exposure and response prevention","Free association","Reassurance seeking","Thought suppression"],0,"ERP faces feared triggers while resisting compulsions."],
["Assessment","Psychometrics","Medium","A test that predicts a future outcome shows good:",["Predictive validity","Test-retest reliability","Inter-rater reliability","Internal consistency"],0,"Predictive validity is a form of criterion-related validity."],
["Assessment","Clinical Interviewing","Easy","Which question type best invites a detailed client account?",["Open-ended","Closed","Leading","Double-barrelled"],0,"Open questions encourage elaboration. Closed questions elicit brief answers."],
["Assessment","Cognitive Testing","Medium","The Wechsler scales primarily assess:",["Intellectual ability","Personality traits","Depressive symptoms","Substance use"],0,"Wechsler scales are standardised measures of cognitive ability."],
["Psychotherapy","Psychodynamic","Medium","Free association is most associated with:",["Psychodynamic therapy","Behavioural activation","Exposure therapy","DBT skills training"],0,"Free association helps surface unconscious material in psychodynamic work."],
["Psychotherapy","Interpersonal Therapy","Medium","Interpersonal therapy focuses mainly on:",["Current relationship problems and role transitions","Early childhood dreams","Cognitive distortions only","Physiological arousal"],0,"IPT targets grief, role disputes, role transitions and interpersonal deficits."],
["Psychotherapy","Family Therapy","Medium","Systemic family therapy views symptoms as:",["Maintained within relationship patterns","Only individual weaknesses","Purely genetic","Unrelated to context"],0,"Systemic approaches examine interaction patterns within the family system."],
["Research & Statistics","Sampling","Medium","A representative sample mainly improves:",["External validity","Internal validity only","Randomisation","Blinding"],0,"Representative sampling supports generalising results to the wider population."],
["Research & Statistics","Effect Size","Medium","An effect size tells you:",["The magnitude of an effect","Whether the null hypothesis is true","The sample size needed","Whether a study is ethical"],0,"Effect sizes complement p-values by showing practical magnitude."],
["Ethics","Competence","Easy","Practising within the boundaries of competence means:",["Offering only services you are trained and supervised to provide","Trying any treatment requested","Avoiding supervision","Ignoring new evidence"],0,"Practitioners work within their training and seek supervision when needed."],
["Ethics","Record Keeping","Easy","Clinical records should be:",["Accurate and stored securely as policy requires","Shared freely","Deleted after each session","Left unsecured"],0,"Accurate, secure records support safe care and accountability."]
);
// ---- Expansion: more topics, questions, glossary ----
NOTES[0].k.push("Psychotic disorders: positive symptoms (delusions, hallucinations) and negative symptoms (avolition, blunted affect)","Personality disorders: Cluster A odd/eccentric, B dramatic/emotional, C anxious/fearful","Eating disorders: anorexia nervosa, bulimia nervosa, binge-eating disorder","Substance use: tolerance, withdrawal and craving; motivational interviewing supports change","Hypomania is milder than mania and does not cause marked impairment");
NOTES[0].a="Clinicians match symptom pattern, duration and impairment to criteria, screen for risk and comorbidity, and plan evidence-based care.";
NOTES[1].a="Graded exposure for phobias, exposure and response prevention for OCD, and CBT for panic and generalised anxiety.";
NOTES[2].a="Combine interview, observation and standardised measures, check reliability and validity, and write a formulation rather than relying on one score.";
NOTES[3].a="Match therapy to the problem: behavioural activation for low mood, exposure for anxiety, DBT skills for emotion dysregulation, IPT for relationship-related distress.";
NOTES[4].a="Read studies critically: check design, confounds, sampling, effect sizes and confidence intervals before trusting a result.";
NOTES[5].a="Explain confidentiality limits at the start, obtain consent (and assent for children), keep boundaries, and consult when unsure.";
NOTES[6].a="Neuropsychological testing describes cognitive strengths and weaknesses. Developmental knowledge shapes age-appropriate assessment.";
NOTES[6].k.push("Hippocampus supports forming new declarative memories","Broca's area damage gives non-fluent speech; Wernicke's gives fluent but disorganised speech","Ainsworth's Strange Situation assesses infant attachment style");
NOTES.push({s:"Clinical Foundations",t:"Foundations: Models, Formulation and Evidence",o:"Clinical psychology applies psychological science to understanding and reducing distress. Modern practice is shaped by explanatory models, individual formulation and evidence.",k:["Biopsychosocial model: biological, psychological and social factors interact","Diathesis-stress: vulnerability plus stressors","Formulation covers predisposing, precipitating, perpetuating and protective factors","Evidence-based practice: research evidence, clinical expertise and client preferences","Wundt opened the first experimental psychology laboratory (1879)","Categorical diagnoses versus dimensional severity"],a:"Formulation guides which intervention to choose and how to explain difficulties to the client.",x:"Know each model's core idea and the four Ps of formulation.",m:"A diagnosis is not a formulation."},{s:"Health Psychology",t:"Health Psychology and Behaviour Change",o:"Health psychology studies how thinking, behaviour and social context influence physical health, illness and recovery.",k:["Health Belief Model: susceptibility, severity, benefits and barriers","Stress and coping: appraisal of demands versus resources","Transtheoretical model: precontemplation to maintenance","Motivational interviewing strengthens the person's own reasons for change","Adherence improves with collaborative planning"],a:"Tailor advice to the person's stage of change and address practical barriers.",x:"Link each model to the factor it emphasises.",m:"Providing information alone rarely changes behaviour."});
Q.push(
["Clinical Foundations","Formulation","Medium","A case formulation is best described as:",["A working explanation of why a person's difficulties developed and persist","A list of diagnoses","A summary of test scores","A treatment contract"],0,"Formulation links predisposing, precipitating, perpetuating and protective factors."],
["Clinical Foundations","Biopsychosocial Model","Easy","The biopsychosocial model proposes that mental health is shaped by:",["Biological, psychological and social factors together","Genetics alone","Learning alone","Culture alone"],0,"It integrates several levels of explanation."],
["Clinical Foundations","Diathesis-Stress","Medium","The diathesis-stress model suggests disorders arise from:",["Vulnerability interacting with stressors","Stress alone","Vulnerability alone","Chance only"],0,"Neither factor alone is sufficient; their interaction matters."],
["Clinical Foundations","Evidence-Based Practice","Medium","Evidence-based practice integrates:",["Research evidence, clinical expertise and client preferences","Research evidence only","Therapist intuition only","Treatment manuals only"],0,"It balances research, expertise and client values."],
["Clinical Foundations","History","Easy","Wilhelm Wundt is credited with founding:",["The first experimental psychology laboratory","Psychoanalysis","Behaviourism","Person-centred therapy"],0,"Wundt opened his Leipzig laboratory in 1879."],
["Clinical Foundations","Diagnosis","Hard","Compared with a categorical approach, a dimensional approach emphasises:",["Severity along a continuum","Present or absent diagnoses","Only biological markers","Only behavioural signs"],0,"Dimensional models describe degrees of symptoms."],
["Health Psychology","Health Behaviour","Medium","The Health Belief Model predicts behaviour from:",["Perceived susceptibility, severity, benefits and barriers","Personality type only","Income only","Age only"],0,"Beliefs about threat and about action shape behaviour."],
["Health Psychology","Stress","Medium","In Lazarus and Folkman's model, stress depends on:",["Appraisal of demands and coping resources","Stimulus intensity only","Genes only","Diet only"],0,"Primary and secondary appraisal shape the response."],
["Health Psychology","Behaviour Change","Medium","The transtheoretical model describes change as:",["A series of stages, from precontemplation to maintenance","A single event","Random","Fixed by personality"],0,"People move through stages and may relapse."],
["Health Psychology","Motivational Interviewing","Easy","Motivational interviewing aims to:",["Strengthen the person's own motivation for change","Confront and persuade","Give orders","Avoid discussing change"],0,"It is collaborative and evokes the person's own reasons."],
["Health Psychology","Adherence","Easy","Treatment adherence is best supported by:",["Collaborative planning and tackling barriers","Blaming the patient","Complex regimens","Avoiding discussion"],0,"Practical, shared planning improves adherence."],
["Psychopathology","Psychotic Disorders","Medium","Which is a negative symptom of schizophrenia?",["Reduced motivation (avolition)","Hallucinations","Delusions","Disorganised speech"],0,"Negative symptoms are reductions in normal functioning."],
["Psychopathology","Personality Disorders","Medium","Cluster A personality disorders are characterised by:",["Odd or eccentric features","Dramatic and emotional features","Anxious and fearful features","Elevated mood"],0,"Cluster A includes paranoid, schizoid and schizotypal."],
["Psychopathology","Bipolar Disorders","Hard","Compared with mania, hypomania is:",["Less severe, without marked impairment or psychosis","Longer lasting","Always needing hospital care","Defined by hallucinations"],0,"Hypomania is milder and shorter."],
["Psychopathology","Trauma","Medium","Acute stress disorder is diagnosed when symptoms last:",["3 days to 1 month after trauma","More than 3 months","Exactly 1 year","Under 1 day"],0,"Beyond one month, PTSD may be considered."],
["Psychopathology","Eating Disorders","Medium","Binge-eating disorder differs from bulimia nervosa because it has:",["No regular compensatory behaviours","No binge episodes","A required low body weight","Required purging"],0,"BED involves binges without regular compensation."],
["Psychopathology","Neurodevelopmental","Easy","ADHD is characterised by persistent:",["Inattention and/or hyperactivity-impulsivity","Fixed delusions","Panic attacks","Binge eating"],0,"These patterns impair functioning across settings."],
["Anxiety & OCD","Specific Phobia","Easy","Which treatment is most effective for specific phobia?",["Graded exposure","Free association","Avoidance","Reassurance"],0,"Graded exposure reduces fear through new learning."],
["Psychopathology","Trauma","Medium","Trauma-focused CBT for PTSD emphasises:",["Processing the trauma memory and unhelpful appraisals","Avoiding reminders","Relaxation only","Ignoring symptoms"],0,"It targets memory processing and appraisals."],
["Assessment","Psychometrics","Hard","Cronbach's alpha estimates:",["Internal consistency","Test-retest stability","Criterion validity","Sensitivity"],0,"It shows how consistently items measure one construct."],
["Assessment","Norms","Medium","A T-score has a mean of:",["50","100","0","15"],0,"T-scores have a mean of 50 and SD of 10."],
["Assessment","Cognitive Testing","Hard","Performance validity tests check whether:",["Effort on cognitive tests is adequate","Intelligence is high","Depression is present","Attachment is secure"],0,"They help judge whether scores reflect true ability."],
["Psychotherapy","CBT","Medium","Behavioural activation for depression involves:",["Scheduling valued, rewarding activities","Dream analysis","Withdrawing from activity","Interpretation of transference"],0,"Activity scheduling counters withdrawal and low mood."],
["Psychotherapy","Therapeutic Alliance","Easy","The therapeutic alliance includes:",["Bond, agreed goals and agreed tasks","Advice only","Therapist authority","Payment terms"],0,"A strong alliance predicts outcome across approaches."],
["Psychotherapy","DBT","Hard","Which is a DBT skills module?",["Distress tolerance","Free association","Dream work","Genogram"],0,"Modules: mindfulness, distress tolerance, emotion regulation, interpersonal effectiveness."],
["Psychotherapy","Behaviour Therapy","Medium","Systematic desensitisation pairs:",["Graded exposure with relaxation","Punishment with exposure","Interpretation with advice","Reassurance with avoidance"],0,"Relaxation is used while facing a fear hierarchy."],
["Research & Statistics","Hypothesis Testing","Hard","A p-value of .03 means:",["If the null were true, results this extreme would occur about 3% of the time","There is a 97% chance the hypothesis is true","The effect is large","The result will replicate"],0,"A p-value is not the probability that a hypothesis is true."],
["Research & Statistics","Design","Medium","A confounding variable is one that:",["Is related to both predictor and outcome","Is always the outcome","Is measured perfectly","Has no effect"],0,"Confounds can create misleading associations."],
["Research & Statistics","Tests","Medium","Which test compares the means of two independent groups?",["Independent-samples t-test","Chi-square test","Pearson correlation","Paired t-test"],0,"A paired t-test is for related measurements."],
["Ethics","Consent","Medium","With a child client, consent usually involves:",["Assent from the child and consent from a guardian, per local law","The child alone always","No one","The therapist alone"],0,"Requirements vary by jurisdiction and age."],
["Ethics","Cultural Competence","Easy","Culturally responsive practice means:",["Considering culture, context and identity in care","Ignoring cultural differences","Assuming shared norms","Using one approach for all"],0,"Culture affects presentation, assessment and engagement."],
["Neuropsychology & Development","Memory","Medium","Hippocampal damage most affects:",["Forming new declarative memories","Basic vision","Reflexes","Motor speed"],0,"The hippocampus supports new declarative memory."],
["Neuropsychology & Development","Attachment","Medium","Ainsworth's Strange Situation assesses:",["Infant attachment style","IQ","Language","Memory span"],0,"It classifies secure and insecure attachment patterns."],
["Neuropsychology & Development","Aphasia","Hard","Broca's area damage typically produces:",["Non-fluent speech with relatively preserved comprehension","Fluent nonsense speech","Loss of vision","Amnesia only"],0,"Wernicke's damage gives fluent but disorganised speech."]
);
GLOSS.push(["Aetiology","The causes or origins of a disorder."],["Attachment","An enduring emotional bond, typically between infant and caregiver."],["Behavioural activation","Scheduling rewarding, valued activities to improve mood."],["Cognitive distortion","A biased, unhelpful pattern of thinking."],["Compulsion","A repetitive act performed to reduce distress from an obsession."],["Confounding variable","A variable related to both predictor and outcome that distorts their relationship."],["Countertransference","The therapist's emotional reaction to the client."],["Effect size","The magnitude of a difference or relationship."],["Exposure","Deliberate, repeated contact with a feared stimulus."],["Extinction","Weakening of a learned response when it is no longer reinforced."],["Habituation","Reduced response to a repeated stimulus."],["Mania","A distinct period of elevated or irritable mood with increased energy."],["Neuroplasticity","The brain's ability to change with experience."],["Obsession","Recurrent, intrusive thoughts, urges or images causing distress."],["Psychosis","Loss of contact with reality, such as delusions or hallucinations."],["Relapse prevention","Planning to maintain gains and manage setbacks."],["Schema","A core belief pattern that organises experience."],["Stigma","Negative social attitudes toward people with mental health conditions."],["Working memory","Holding and manipulating information over short periods."],["Diathesis","A predisposing vulnerability to a disorder."]);
